networks:
  net:
    driver: overlay
    attachable: true
  proxylampy:
    external: true
  serverlampy:
    external: true
services:
  www:
    image: koromerzhin/php:8.4.13-apache-symfony
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ${PWD}/apps:/var/www/:rw
      - ${PWD}/conf/php.ini-development://usr/local/etc/php/conf.d/php.ini
      - ${PWD}/conf/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro
      - ${PWD}/conf/apache2/apache2.conf:/etc/apache2/apache2.conf:ro
    environment:
      APP_SECRET: "CHANGEME"
      MAILER_DSN: "smtp://mailtest:1025"
      MESSENGER_TRANSPORT_DSN: "doctrine://default"
      LOCK_DNS: semaphore
      DATABASE_BDD: sylius_bdd
      DATABASE_USER: sylius
      DATABASE_PASSWORD: password
      DATABASE_URL: "mysqli://sylius:password@mariadb:3306/sylius_bdd"
    networks:
      - net
      - serverlampy
      - proxylampy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sylius.rule=Host(`sylius.traefik.me`)"
        - "traefik.http.routers.sylius-tls.tls.domains[0].main=sylius.traefik.me"
        - "traefik.http.routers.sylius.tls=true"
        - "traefik.http.services.sylius.loadbalancer.server.port=80"