version: "3.4"

networks:
  proxylampy:
    external: true
  serverlampy:
    external: true
services:
  apache:
    networks:
      - net
      - proxylampy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sylius.rule=Host(`sylius.traefik.me`)"
        - "traefik.http.routers.sylius-tls.tls.domains[0].main=sylius.traefik.me"
        - "traefik.http.routers.sylius.tls=true"
        - "traefik.http.services.sylius.loadbalancer.server.port=80"
  phpfpm:
    networks:
      - net
      - serverlampy
